# ============================================
#  Mosquitto config — Cold-chain demo (M1)
# ============================================

# Lắng nghe MQTT trên cổng chuẩn 1883
listener 1883

# Cho phép kết nối ẩn danh (demo nội bộ)
allow_anonymous true

# Lưu tin nhắn bền vững
persistence true
persistence_location /mosquitto/data/

# Đưa log ra stdout
log_dest stdout
log_type all
